openapi: 3.0.2
x-stoplight:
  id: ma4m98588hemj
info:
  title: tsunagaru
  version: '1.0'
  description: tsunagaru
  contact:
    name: tsunagaru
    email: codeyy021@gmail.com
servers:
  - url: 'http://localhost:8080'
    description: Local server
paths:
  '/users/{uid}':
    patch:
      summary: UpdateUser
      operationId: update-user
      tags:
        - user
      responses:
        '200':
          $ref: '#/components/responses/UpdateUserResponse'
      description: |-
        ユーザー情報を更新する際に使用するapi。
        uidを元に、テーブルの追加か更新かを判断する
      requestBody:
        $ref: '#/components/requestBodies/UpdateUserRequest'
    parameters:
      - schema:
          type: string
        name: uid
        in: path
        required: true
tags:
  - name: user
    description: ''
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: mk7chflgfopnk
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        uid:
          type: string
          description: Discordログインした際に取得できるIDを、UUIDとして登録する
        email:
          type: string
        bio:
          type: string
        icon_image_url:
          type: string
        company:
          type: string
        status:
          type: string
          enum:
            - Frontend
            - Backend
            - Mobile
            - AI
            - Infra
            - Other
          description: フロントエンドエンジニアなどのエンジニアとして詳細情報
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        twitter_url:
          type: string
        github_url:
          type: string
        instagram_url:
          type: string
        web_url:
          type: string
        zenn_url:
          type: string
        qiita_url:
          type: string
      required:
        - id
        - name
        - uid
        - email
  requestBodies:
    UpdateUserRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              company:
                type: string
              job:
                type: string
              status:
                type: string
                description: フロントエンドエンジニアなどのエンジニアとして詳細情報
              bio:
                type: string
              icon_image_url:
                type: string
              twitter_url:
                type: string
              github_url:
                type: string
              instagram_url:
                type: string
              web_url:
                type: string
              zenn_url:
                type: string
              qiita_url:
                type: string
      description: ''
  responses:
    UpdateUserResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      headers: {}
