/* tslint:disable */
/* eslint-disable */
/**
 * tsunagaru
 * tsunagaru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: codeyy021@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name: string;
    /**
     * Discordログインした際に取得できるIDを、UUIDとして登録する
     * @type {string}
     * @memberof User
     */
    uid: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    iconImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    company?: string;
    /**
     * フロントエンドエンジニアなどのエンジニアとして詳細情報
     * @type {string}
     * @memberof User
     */
    status?: UserStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    twitterUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    githubUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    instagramUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    webUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    zennUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    qiitaUrl?: string;
}


/**
 * @export
 */
export const UserStatusEnum = {
    Frontend: 'Frontend',
    Backend: 'Backend',
    Mobile: 'Mobile',
    Ai: 'AI',
    Infra: 'Infra',
    Other: 'Other'
} as const;
export type UserStatusEnum = typeof UserStatusEnum[keyof typeof UserStatusEnum];


/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "uid" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'uid': json['uid'],
        'email': json['email'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'iconImageUrl': !exists(json, 'icon_image_url') ? undefined : json['icon_image_url'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'twitterUrl': !exists(json, 'twitter_url') ? undefined : json['twitter_url'],
        'githubUrl': !exists(json, 'github_url') ? undefined : json['github_url'],
        'instagramUrl': !exists(json, 'instagram_url') ? undefined : json['instagram_url'],
        'webUrl': !exists(json, 'web_url') ? undefined : json['web_url'],
        'zennUrl': !exists(json, 'zenn_url') ? undefined : json['zenn_url'],
        'qiitaUrl': !exists(json, 'qiita_url') ? undefined : json['qiita_url'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'uid': value.uid,
        'email': value.email,
        'bio': value.bio,
        'icon_image_url': value.iconImageUrl,
        'company': value.company,
        'status': value.status,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'twitter_url': value.twitterUrl,
        'github_url': value.githubUrl,
        'instagram_url': value.instagramUrl,
        'web_url': value.webUrl,
        'zenn_url': value.zennUrl,
        'qiita_url': value.qiitaUrl,
    };
}

