/* tslint:disable */
/* eslint-disable */
/**
 * tsunagaru
 * tsunagaru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: codeyy021@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class HealthcheckApi extends runtime.BaseAPI {

    /**
     * healthcheck
     * healthcheck
     */
    async getHealthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/healthcheck`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * healthcheck
     * healthcheck
     */
    async getHealthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getHealthcheckRaw(initOverrides);
        return await response.value();
    }

}
