/*
 * tsunagaru
 *
 * tsunagaru
 *
 * API version: 1.0
 * Contact: codeyy021@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateUserRequest struct {

	Name string `json:"name"`

	IconImageUrl string `json:"icon_image_url"`
}

// AssertCreateUserRequestRequired checks if the required fields are not zero-ed
func AssertCreateUserRequestRequired(obj CreateUserRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"icon_image_url": obj.IconImageUrl,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCreateUserRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateUserRequest (e.g. [][]CreateUserRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateUserRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateUserRequest, ok := obj.(CreateUserRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateUserRequestRequired(aCreateUserRequest)
	})
}
