name: Deploy to Railway

on:
  push:
    branches: [main]
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: go deploy
        run: cd server && ./deploy.sh

      - name: Install Railway
        run: npm i @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: 5561f710-da68-4449-a382-b39e627891c5
