on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/deploy_app_testnet.yml"

name: Build and Deploy Testnet App to Cloud Run

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm i

      - name: build openapi
        run: |
          npm run openapi

      - name: Deploy to netlify
        run: npx netlify-cli deploy --dir=./dist
        env:
          NETLIFY_AUTH_TOKEN: M9AHeEfRGInFQwecm6IQp_ItnDb3BIxeqZDa5G8lKwU
          NETLIFY_SITE_ID: 1984aa77-cdeb-46ee-8d75-13d053e6111e
